name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite
  workflow_dispatch:      # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar animação da cobrinha estilizada
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rodrigoscast
          outputs: |
            dist/github-snake.svg
          snake_color: "#06b6d4"
          background: "#0a0a0a"
          color_snake: "#06b6d4"
          color_dots: "#1e293b,#334155,#475569"

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
